[build]
  command = "npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend"
  node_bundler = "esbuild"
  # This tells Netlify to treat all .js files as ESM
  included_files = ["backend/package.json"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
